version: '3.8'

services:
  backend:
    build: ./Backend
    ports:
      - "3001:3001"
    networks:
      - my_network
    env_file:
      - ./Backend/config.env
  
  frontend:
    build: ./Frontend
    ports: 
      - "5173:5173"
    networks:
      - my_network
    env_file:
      - ./Frontend/.env

networks:
  my_network:
    driver: bridge
